Added docs for telegram clode plugin.
itransition-atlassian/itransition-atlassian.github.io pull request #6
Opened 2023-09-25 14:13 UTC by AlexanderGerasimovich

2023-09-26 09:10 UTC, itransition-atlassian requested changes

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/overview.html
> +        <li>Receive notifications about issue status from telegram bot.</li>
`Telegram bot`

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/overview.html
> +        <li>Post messages from telegram chat to linked issue in Jira.</li>
please write `Telegram` first letter with upper case

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/user-registration.html
> +
please remove extra lines

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/admin-guide.html
> +<p><b>User authorization:</b></p>
`Admin User Authorization:`

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/admin-guide.html
> +        After installing the plugin click on "Configure" or "Global Settings".
do we have `Configure` page??

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/admin-guide.html
> +        You will be authenticated as an admin, so your account will be used for sending confirmation messages during other users registration.
>> your account will be used for sending confirmation messages during other users registration

what does this mean? do we really use admin account to send any messages?

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/admin-guide.html
> +<p><b>Note:</b> An Admin account and Bot are required for the plugin to work. If you press <b>"Log out"</b> button, <b>the plugin will stop working!</b> And most importantly, <b>do not remove the bot
if admin log out, will all other users stop receiving the notifications?

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/bot-abilities.html
> +<p>Gives you a wonderful opportunity to manage your projects via the popular messenger <b>Telegram</b> which makes your work much more convenient.</p>
`Bot gives you...`

2023-09-26 09:10 UTC, itransition-atlassian commented on telegram/cloud/bot-abilities.html
> +<p><b>Jira Bot</b> will notify you about everything you decide is important! If an issue or chat for an issue was deleted, the bot sends a notification to this chat and leaves it.</p>
please check my comment in the wiki

2023-09-26 12:15 UTC, AlexanderGerasimovich commented on telegram/cloud/admin-guide.html
> +        After installing the plugin click on "Configure" or "Global Settings".
The 'Configure' button and the 'Global Settings' link lead to the same configuration page.

2023-09-26 12:27 UTC, AlexanderGerasimovich commented on telegram/cloud/admin-guide.html
> +        You will be authenticated as an admin, so your account will be used for sending confirmation messages during other users registration.
Only an administrator can access the Configure page.

2023-09-27 13:23 UTC, itransition-atlassian approved these changes

2023-09-28 08:49 UTC, merged